baseurl: /guides-template
markdown: redcarpet
name: 18F Guides Template
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty
highlighter: rouge

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Adding a new page
  url: adding-a-new-page/
  internal: true
  children:
  - text: Making a child page
    url: making-a-child-page/
    internal: true
- text: Adding images
  url: adding-images/
  internal: true
- text: Updating the config file
  url: updating-the-config-file/
  internal: true
- text: GitHub setup
  url: github-setup/
  internal: true
- text: Post your guide
  url: post-your-guide/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/guides-template

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
