name: Federalist Documentation

theme: uswds-jekyll

title: Federalist Docs

google_analytics_ua: UA-48605964-19

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      sidenav: "sidenav"

styles:
  - /assets/main.css

plugins:
  - jekyll-redirect-from
