markdown: redcarpet
name: Federalist Documentation
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F - Federalist
  url: https://federalist.18f.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /uploads/logo.svg
logoalt: Federalist logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About Federalist
  url: index.html
  internal: true
- text: Using Federalist
  url: pages/using-federalist/
  internal: true
- text: Custom Templates
  url: pages/custom-templates
  internal: true

repos:
- name: Federalist
  description: Main repository
  url: https://github.com/18F/federalist

back_link:
  url: "https://federalist.18f.gov/"
  text: Back to Federalist

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
