title: Federalist Documentation
name: Federalist Documentation
theme: uswds-jekyll

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-31

# Configuration for DAP, add your agency ID here:
dap_agency: GSA



defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      sidenav: "sidenav"

styles:
  - /assets/main.css

plugins:
  - jekyll-redirect-from
