title: Federalist Homepage
name: Federalist Homepage
theme: uswds-jekyll

url: "https://federalist.18f.gov" 

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-31

# Configuration for DAP, add your agency ID here:
dap_agency: GSA

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: federalist

support_email: federalist-support@gsa.gov

collections:
  pages:
    output: true
    permalink: /:path/
#
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "page"
#       sidenav: "sidenav"
#   - scope:
#       path: ""
#       type: templates
#     values:
#       layout: "default"

scripts:
  - /assets/js/glossary.js
  - /assets/js/index.js
  - /assets/uswds/js/uswds.min.js

styles:
  - /assets/css/site.css

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  
# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: 18F
  repository: federalist.18f.gov
  default_branch: master
