title: Federalist Documentation
name: Federalist Documentation
theme: uswds-jekyll

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-48605964-31

# Configuration for DAP, add your agency ID here:
dap_agency: GSA

edit_page:
  text: Edit this page

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: federalist-docs

collections:
  templates:
    output: true
    permalink: /pages/using-federalist/templates/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      sidenav: "sidenav"
  - scope:
      path: ""
      type: templates
    values:
      layout: "template"

scripts:
  - /assets/js/glossary.js
  - /assets/js/index.js

styles:
  - /assets/css/site.css

plugins:
  - jekyll-redirect-from
