---
############################
#  SHARED


############################
#  JOBS

jobs:
  - name: test
    plan:
      - get: pr
        trigger: true
        version: every
      - put: pr
        params:
          path: pr
          status: pending
          base_context: concourse
          context: test
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.7
          inputs: [name: pr]
          run:
            dir: pr
            path: bash
            args:
              - -c
              - |
                bundle install
                bundle exec rspec spec
                bundle exec htmlproofer ./_site --disable-external
    on_failure:
      in_parallel:
        - put: pr
          params:
            path: pr
            status: failure
            base_context: concourse
            context: test
        - put: slack
          params:
            text: |
              :x: FAILED: pages docs tests on staging
              ((build-url))
              <@U01J8B463T5> <@U01J0M3E8NS> <@U01J7LKV5MZ>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))                
    on_success:
      in_parallel:
        - put: pr
          params:
            path: pr
            status: success
            base_context: concourse
            context: test
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully tested pages docs on staging
              ((build-url))
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))                       

############################
#  RESOURCES

resources:

  - name: pr
    type: pull-request
    check_every: 5m
    source:
      repository: 18F/federalist.18f.gov
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))


############################
#  RESOURCE TYPES

resource_types:

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource